# Generated by Django 5.2.13 on 2026-04-24 01:51

import django.db.models.deletion
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nro_doc', models.CharField(max_length=15, unique=True, verbose_name='Número de Documento')),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda], verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo], verbose_name='Peso (Kg)')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('DE', 'Devuelto')], default='PE', max_length=2, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio Total')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='encomiendas_recibidas', to='clientes.cliente')),
                ('empleado_registra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='encomiendas_registradas', to='envios.empleado')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='encomiendas_enviadas', to='clientes.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='encomiendas', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('DE', 'Devuelto')], max_length=2, null=True)),
                ('estado_nuevo', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('DE', 'Devuelto')], max_length=2)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='envios.empleado')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
