# Generated by Django 6.0.4 on 2026-04-30 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linea', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupoarticulo')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupoarticulo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lineaarticulo')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('precio_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('precio_4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listaprecio', to='core.articulo')),
            ],
        ),
    ]
